[tool.poetry]
name = "feed-sinai"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "feed_sinai"}]
package-mode = false

[tool.poetry.dependencies]
python = "^3.8"
pysolr = "^3.8"
requests = "2.22"
click = "^8.1.3"
rich = "^13.4.1"
python-dateutil = "^2.8.2"
pyyaml = "^6.0.1"

[tool.poetry.group.dev.dependencies]
mypy = "*"
pytest = "*"
pytest-mypy = "*"
pytest-pylint = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
