# pyright: reportInvalidTypeForm=false
# pylint: disable=too-many-lines
"""Pydantic classes for the data model."""

from datetime import datetime
from enum import Enum
from pathlib import Path
from typing import List, Optional, Annotated, Self, Set, TypeVar
from uuid import UUID

from pydantic import (
    AnyUrl,
    BaseModel as PydanticBaseModel,
    computed_field,
    Field,
    StringConstraints,
    ConfigDict,
    model_validator,
)


SiblingModel = TypeVar("SiblingModel", bound=PydanticBaseModel)


class BaseModel(PydanticBaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True)

    def convert(self, cls: type[SiblingModel], **updated_data) -> SiblingModel:
        data = (
            self.model_dump(
                exclude_unset=True, exclude_none=True, exclude_defaults=True
            )
            | updated_data
        )
        return cls(**data)

    def deep_get(self, *names: str) -> set[str]:
        result = set()

        for name in names:
            value = getattr(self, name, [])
            if isinstance(value, List):
                result.update(value)
            elif value:
                # Don't add if value == None
                result.add(value)

        for field_name in self.__class__.model_fields:
            field_value = getattr(self, field_name, [])
            if isinstance(field_value, List):
                for obj in field_value:
                    if hasattr(obj, "deep_get"):
                        result.update(obj.deep_get(*names))
            else:
                if hasattr(field_value, "deep_get"):
                    result.update(field_value.deep_get(*names))

        return result


NonEmptyStr = Annotated[
    str,
    StringConstraints(min_length=1),
]

Ark = Annotated[
    str,
    StringConstraints(pattern=r"^ark:/21198/([a-z]|[0-9])+"),
]


class ControlledTerm(BaseModel):
    id: NonEmptyStr
    label: NonEmptyStr


# generated by datamodel-codegen:
#   filename:  agent.schema.json
#   timestamp: 2025-05-28T17:21:15+00:00


class Iso(BaseModel):
    not_before: Annotated[
        str,
        StringConstraints(min_length=4),
    ]
    not_after: Optional[
        Annotated[
            str,
            StringConstraints(min_length=1),
        ]
    ] = None


class Date(BaseModel):
    value: Optional[NonEmptyStr] = None
    iso: Iso


class RelatedConceptSource(Enum):
    HAF = "HAF"
    LoC = "LoC"
    Perseus = "Perseus"
    Pinakes = "Pinakes"
    Pleiades = "Pleiades"
    Syriaca = "Syriaca"
    VIAF = "VIAF"


class RelConItem(BaseModel):
    label: NonEmptyStr
    uri: AnyUrl
    source: RelatedConceptSource


class ReferenceNumberSource(Enum):
    CPG = "CPG"
    CPL = "CPL"
    TLG = "TLG"


class RefnoItem(BaseModel):
    label: NonEmptyStr
    idno: NonEmptyStr
    source: ReferenceNumberSource


class BibItem(BaseModel):
    id: UUID
    type: ControlledTerm
    range: Optional[NonEmptyStr] = None
    alt_shelf: Optional[NonEmptyStr] = None
    url: Optional[NonEmptyStr] = None
    note: Optional[List[str]] = None


class RelItem(BaseModel):
    id: NonEmptyStr
    label: NonEmptyStr


class RelAgentItem(BaseModel):
    id: Ark = Field(..., description="A unique Archival Resource Key (ARK)")
    source: Optional[List[str]] = None
    rel: List[RelItem]


class RelPlaceItem(BaseModel):
    id: Ark = Field(..., description="A unique Archival Resource Key (ARK)")
    source: Optional[List[str]] = None
    rel: List[RelItem]


class CataloguerItem(BaseModel):
    message: NonEmptyStr
    contributor: Optional[NonEmptyStr] = Field(
        None,
        description="The person responsible for the intellectual contributions made to the record via this change",
    )
    added_by: NonEmptyStr = Field(
        ...,
        description="The user account responsible for editing the JSON record, likely supplied by the content management system",
    )
    timestamp: datetime


class Agent(BaseModel):
    ark: Ark
    type: ControlledTerm
    pref_name: NonEmptyStr
    alt_name: Optional[List[NonEmptyStr]] = None
    desc: Optional[NonEmptyStr] = None
    gender: Optional[ControlledTerm] = None
    birth: Optional[Date] = None
    death: Optional[Date] = None
    floruit: Optional[Date] = None
    rel_con: Optional[List[RelConItem]] = None
    refno: Optional[List[RefnoItem]] = None
    bib: Optional[List[BibItem]] = None
    note: Optional[List[str]] = None
    rel_agent: Optional[List[RelAgentItem]] = None
    rel_place: Optional[List[RelPlaceItem]] = None
    internal: Optional[List[str]] = None
    cataloguer: Optional[List[CataloguerItem]] = None


# generated by datamodel-codegen:
#   filename:  work.schema.json
#   timestamp: 2025-05-28T17:23:18+00:00


class Creation(BaseModel):
    value: Optional[NonEmptyStr] = None
    iso: Iso


# TODO: not attested
class Incipit(BaseModel):
    value: NonEmptyStr
    translation: Optional[List[str]] = None
    source: Optional[List[str]] = None


# TODO not attested
class Explicit(BaseModel):
    value: NonEmptyStr
    translation: Optional[List[str]] = None
    source: Optional[List[str]] = None


# TODO not attested
class RelWorkItem(BaseModel):
    id: Ark
    source: Optional[List[str]] = None
    rel: List[RelItem]


class AssocNameItem(BaseModel):
    id: Optional[Ark] = None
    value: Optional[NonEmptyStr] = None
    as_written: Optional[NonEmptyStr] = None
    role: ControlledTerm
    note: Optional[List[str]] = None


class AssocNameItemMerged(AssocNameItem):
    agent: Optional[Agent] = None

    @model_validator(mode="after")
    def agent_record_loaded(self) -> Self:
        if self.id and not self.agent:
            raise ValueError("has agent id but agent record not loaded")
        return self


class AssocNameItemUnmerged(AssocNameItem):
    agent: None = None

    def merge(self, base_dir):
        return self.convert(AssocNameItemMerged, agent=Agent.load(self.id))


class ConceptualWork(BaseModel):
    ark: Ark
    pref_title: NonEmptyStr
    orig_lang: Optional[ControlledTerm] = None
    orig_lang_title: Optional[NonEmptyStr] = None
    alt_title: Optional[List[NonEmptyStr]] = None
    desc: Optional[NonEmptyStr] = None
    genre: Optional[List[ControlledTerm]] = None
    creator: List[AssocNameItemUnmerged] | List[AssocNameItemMerged] | None = None
    creation: Optional[Creation] = None
    incipit: Optional[Incipit] = None
    explicit: Optional[Explicit] = None
    rel_con: Optional[List[RelConItem]] = None
    refno: Optional[List[RefnoItem]] = None
    bib: Optional[List[BibItem]] = None
    note: Optional[List[str]] = None
    rel_work: Optional[List[RelWorkItem]] = None
    rel_agent: Optional[List[RelAgentItem]] = None
    rel_place: Optional[List[RelPlaceItem]] = None
    internal: Optional[List[str]] = None
    cataloguer: Optional[List[CataloguerItem]] = None


class ConceptualWorkUnmerged(ConceptualWork):
    creator: Optional[List[AssocNameItemUnmerged]] = None


class ConceptualWorkMerged(ConceptualWork):
    creator: Optional[List[AssocNameItemMerged]] = None


# generated by datamodel-codegen:
#   filename:  text_unit.schema.json
#   timestamp: 2025-05-28T17:22:58+00:00


# TODO: what's up here?
class WorkStub(BaseModel):
    id: Ark


# TODO: what's up here?
class WorkBrief(BaseModel):
    desc_title: Optional[NonEmptyStr] = None
    creator: Optional[List[Ark] | List[Agent]] = Field(None, min_length=1)
    genre: Optional[List[ControlledTerm]] = Field(None, min_length=1)


class WorkBriefUnmerged(WorkBrief):
    creator: Optional[List[Ark]] = Field(None, min_length=1)


class WorkBriefMerged(WorkBrief):
    creator: Optional[List[Agent]] = Field(None, min_length=1)


class ExcerptItem(BaseModel):
    type: ControlledTerm
    locus: Optional[NonEmptyStr] = None
    as_written: Optional[NonEmptyStr] = None
    translation: Optional[List[str]] = None
    note: Optional[List[str]] = None


class Contents(BaseModel):
    label: Optional[NonEmptyStr] = None
    work_id: Optional[Ark] = None
    locus: Optional[NonEmptyStr] = None
    note: Optional[List[str]] = None

    @model_validator(mode="after")
    def has_label_or_work_id(self) -> Self:
        if not (self.label or self.work_id):
            raise ValueError("`Contents.label` and `.work_id` cannot both be None")
        return self


class WorkWitItem(BaseModel):
    work: WorkBrief | WorkStub | ConceptualWorkMerged
    alt_title: Optional[str] = Field(
        None,
        description="An alternative title providing witness-specific information about the work",
    )
    as_written: Optional[NonEmptyStr] = None
    locus: Optional[NonEmptyStr] = None
    excerpt: Optional[List[ExcerptItem]] = None
    contents: Optional[List[Contents]] = None
    note: Optional[List[str]] = None
    bib: Optional[List[BibItem]] = None


class WorkWitItemUnmerged(WorkWitItem):
    work: WorkBriefUnmerged | WorkStub


class WorkWitItemMerged(WorkWitItem):
    work: WorkBriefMerged | ConceptualWorkMerged


class ScriptItem(BaseModel):
    id: NonEmptyStr
    label: NonEmptyStr
    writing_system: str


class AssocPlaceItem(BaseModel):
    # id should be an ark, but it seems to be swapped with the "value" field so it's populated with names instead
    # id: Optional[Ark] = None
    id: Optional[NonEmptyStr] = None
    value: Optional[NonEmptyStr] = None
    as_written: Optional[NonEmptyStr] = None
    event: ControlledTerm
    note: Optional[List[str]] = None


class AssocDateItem(BaseModel):
    value: NonEmptyStr
    iso: Optional[Iso] = None
    type: ControlledTerm
    as_written: Optional[NonEmptyStr] = None
    note: Optional[List[str]] = None


class ParaItem(BaseModel):
    type: ControlledTerm
    locus: NonEmptyStr
    lang: List[ControlledTerm] = Field(..., min_length=1)
    script: Optional[List[ScriptItem]] = Field(None, min_length=1)
    label: Optional[NonEmptyStr] = None
    as_written: Optional[NonEmptyStr] = None
    translation: Optional[List[str]] = None
    assoc_name: Optional[List[AssocNameItem]] = None
    assoc_place: Optional[List[AssocPlaceItem]] = None
    assoc_date: Optional[List[AssocDateItem]] = None
    note: Optional[List[str]] = None


class NoteItem(BaseModel):
    type: ControlledTerm
    value: Optional[NonEmptyStr]


class DescProvenanceProgramItem(BaseModel):
    label: str
    description: str


class DescProvenance(BaseModel):
    program: Optional[List[DescProvenanceProgramItem]] = None
    rights: Optional[str] = None


class TextUnit(BaseModel):
    ark: Ark
    reconstruction: bool
    label: NonEmptyStr
    summary: Optional[NonEmptyStr] = None
    locus: Optional[NonEmptyStr] = None
    lang: List[ControlledTerm] = Field(..., min_length=1)
    work_wit: List[WorkWitItemUnmerged] | List[WorkWitItemMerged] = Field(
        ..., min_length=1
    )
    para: Optional[List[ParaItem]] = None
    features: Optional[List[ControlledTerm]] = None
    note: Optional[List[NoteItem]] = None
    bib: Optional[List[BibItem]] = None
    cataloguer: Optional[List[CataloguerItem]] = None
    reconstructed_from: Optional[List[Ark]] = Field(None, min_length=1)
    parent: List[Ark] = Field(..., min_length=1)
    internal: Optional[List[str]] = None
    desc_provenance: Optional[DescProvenance] = None  # TODO found in data, not schema


class TextUnitUnmerged(TextUnit):
    work_wit: List[WorkWitItemUnmerged] = Field(..., min_length=1)


class TextUnitMerged(TextUnit):
    work_wit: List[WorkWitItemMerged] = Field(..., min_length=1)


# generated by datamodel-codegen:
#   filename:  layer.schema.json
#   timestamp: 2025-05-28T17:21:54+00:00

# from __future__ import annotations

# from datetime import datetime
# from typing import List, Optional
# from uuid import UUID

# from pydantic import AnyUrl, BaseModel, Field, constr


class WritingItem(BaseModel):
    script: List[ScriptItem] = Field(..., min_length=1)
    locus: Optional[NonEmptyStr] = None
    note: Optional[List[str]] = None


class InkItem(BaseModel):
    locus: Optional[NonEmptyStr] = None
    color: Optional[List[str]] = None
    note: Optional[List[str]] = None


class LayoutItem(BaseModel):
    locus: Optional[NonEmptyStr] = None
    columns: Optional[str] = None
    lines: Optional[str] = None
    dim: Optional[NonEmptyStr] = Field(
        None,
        description="A string expression of an object's dimensions, whether manuscript block, folio, or writing area",
    )
    note: Optional[List[str]] = None


class TextUnitStub(BaseModel):
    id: Ark = Field(..., description="A unique Archival Resource Key (ARK)")
    label: NonEmptyStr
    locus: Optional[NonEmptyStr] = None


class Ms(BaseModel):
    label: NonEmptyStr
    id: Optional[Ark] = None
    url: Optional[AnyUrl] = None


class RelatedMs(BaseModel):
    type: ControlledTerm
    label: NonEmptyStr
    note: Optional[List[str]] = None
    mss: List[Ms] = Field(..., min_length=1)


class InscribedLayer(BaseModel):
    ark: Ark
    reconstruction: bool
    state: ControlledTerm = Field(
        ..., description="The current state of the inscribed layer"
    )
    label: NonEmptyStr
    locus: Optional[NonEmptyStr] = None
    summary: Optional[NonEmptyStr] = None
    extent: Optional[NonEmptyStr] = Field(
        None,
        description="The extent, expressed in number of folios, which comprise the manuscript object",
    )
    writing: List[WritingItem] = Field(..., min_length=1)
    ink: Optional[List[InkItem]] = None
    layout: Optional[List[LayoutItem]] = None
    text_unit: List[TextUnitStub] | List[TextUnit] = Field(..., min_length=1)
    para: Optional[List[ParaItem]] = None
    assoc_date: Optional[List[AssocDateItem]] = None
    assoc_name: Optional[List[AssocNameItem]] = None
    assoc_place: Optional[List[AssocPlaceItem]] = None
    features: Optional[List[ControlledTerm]] = None
    related_mss: Optional[List[RelatedMs]] = None
    note: Optional[List[NoteItem]] = None
    bib: Optional[List[BibItem]] = None
    cataloguer: Optional[List[CataloguerItem]] = None
    reconstructed_from: Optional[List[Ark]] = None
    parent: List[Ark] = Field(..., min_length=1)
    internal: Optional[List[str]] = None
    desc_provenance: Optional[DescProvenance] = None  # TODO found in data, not schema


class InscribedLayerUnmerged(InscribedLayer):
    text_unit: List[TextUnitStub] = Field(..., min_length=1)


class InscribedLayerMerged(InscribedLayer):
    text_unit: List[TextUnit] = Field(..., min_length=1)


# generated by datamodel-codegen:
#   filename:  ms_obj.schema.json
#   timestamp: 2025-05-28T17:22:16+00:00

# from __future__ import annotations

# from datetime import datetime
# from enum import Enum
# from typing import List, Optional
# from uuid import UUID

# from pydantic import AnyUrl, BaseModel, Field, constr


class LayerStub(BaseModel):
    id: Ark
    label: NonEmptyStr
    type: ControlledTerm
    locus: Optional[NonEmptyStr] = None


class Part(BaseModel):
    label: Optional[NonEmptyStr] = None
    summary: Optional[NonEmptyStr] = None
    locus: Optional[NonEmptyStr] = None
    support: List[ControlledTerm] = Field(..., min_length=1)
    extent: Optional[NonEmptyStr] = Field(
        None,
        description="The extent, expressed in number of folios, which comprise the manuscript object",
    )
    dim: Optional[NonEmptyStr] = Field(
        None,
        description="A string expression of an object's dimensions, whether manuscript block, folio, or writing area",
    )
    layer: List[LayerStub] | List[InscribedLayerMerged] = Field(..., min_length=1)
    para: Optional[List[ParaItem]] = None
    note: Optional[List[NoteItem]] = None
    related_mss: Optional[List[RelatedMs]] = None


class PartUnmerged(Part):
    layer: List[LayerStub] = Field(..., min_length=1)


class PartMerged(Part):
    layer: List[InscribedLayerMerged] = Field(..., min_length=1)


class LocationItem(BaseModel):
    id: NonEmptyStr
    collection: Optional[str] = None
    repository: NonEmptyStr


class ViscodexItem(BaseModel):
    type: ControlledTerm
    label: NonEmptyStr
    url: AnyUrl


class TextDirection(Enum):
    right_to_left = "right-to-left"
    top_to_bottom = "top-to-bottom"
    bottom_to_top = "bottom-to-top"


class Behavior(Enum):
    paged = "paged"
    individuals = "individuals"


class IiifItem(BaseModel):
    type: ControlledTerm
    manifest: AnyUrl
    text_direction: Optional[TextDirection] = None
    behavior: Optional[Behavior] = None
    thumbnail: Optional[AnyUrl] = None


# TODO only used in unattested class DigProvenance
class Image(BaseModel):
    camera_operator: Optional[List[str]] = None
    imaging_date: Optional[str] = None
    delivery: Optional[str] = None
    msi_processing: Optional[List[str]] = Field(
        None,
        description="Names of the person(s) responsible for processing the MSI data for this record",
    )
    program: Optional[str] = None
    condition_category: Optional[str] = None
    note: Optional[List[str]] = None


# TODO only used in unattested class DigProvenance
class Description(BaseModel):
    program: str
    note: Optional[List[str]] = None


# TODO class not attested in data, replace by DescProvenance and ImageProvenance?
class DigProvenance(BaseModel):
    images: Optional[List[Image]] = None
    descriptions: Optional[List[Description]] = None
    image_rights: NonEmptyStr
    metadata_rights: NonEmptyStr


# TODO attested in all data but only found in the export_test schema
class ImageProvenanceProgramItem(BaseModel):
    label: Optional[str] = None
    description: Optional[str] = None
    camera_operator: Optional[List[str]] = None
    imaging_date: Optional[str] = None
    delivery: Optional[str] = None
    msi_processing: Optional[List[str]] = Field(
        None,
        description="Names of the person(s) responsible for processing the MSI data for this record",
    )
    condition_category: Optional[str] = None
    note: Optional[List[str]] = None

    # TODO: not found in schemas, attested in data
    imaging_system: Optional[str] = None


# TODO attested in all data but only found in the export_test schema
class ImageProvenance(BaseModel):
    program: Optional[List[ImageProvenanceProgramItem]] = None
    rights: Optional[NonEmptyStr] = (
        None  # TODO schema defines as not optional but gives None as default
    )


class ManuscriptObject(BaseModel):
    ark: Ark = Field(..., description="A unique Archival Resource Key (ARK)")
    reconstruction: bool
    type: ControlledTerm
    shelfmark: NonEmptyStr
    summary: Optional[NonEmptyStr] = None
    extent: Optional[NonEmptyStr] = Field(
        ...,
        description="The extent, expressed in number of folios, which comprise the manuscript object",
    )
    weight: Optional[NonEmptyStr] = Field(
        None, description="A string expression of the manuscript object's weight"
    )
    dim: Optional[NonEmptyStr] = Field(
        None,
        description="A string expression of an object's dimensions, whether manuscript block, folio, or writing area",
    )
    state: ControlledTerm = Field(
        ..., description="The current state of the manuscript object"
    )
    fol: Optional[NonEmptyStr] = Field(
        None,
        description="A string expressing the foliation of the object in a semi-controlled format",
    )
    coll: Optional[NonEmptyStr] = Field(
        None,
        description="A string expressing the collation of the object following a semi-controlled format, such as a collational formula",
    )
    features: Optional[List[ControlledTerm]] = None
    part: List[Part] | List[PartUnmerged] | List[PartMerged] = Field(..., min_length=1)
    layer: List[LayerStub] | List[InscribedLayerMerged] | None = Field(
        None, min_length=1
    )
    para: Optional[List[ParaItem]] = None
    location: List[LocationItem]
    assoc_date: Optional[List[AssocDateItem]] = None
    assoc_name: Optional[List[AssocNameItem]] = None
    assoc_place: Optional[List[AssocPlaceItem]] = None
    note: Optional[List[NoteItem]] = None
    related_mss: Optional[List[RelatedMs]] = None
    viscodex: Optional[List[ViscodexItem]] = None
    bib: Optional[List[BibItem]] = None
    iiif: Optional[List[IiifItem]] = None
    internal: Optional[List[str]] = None
    cataloguer: Optional[List[CataloguerItem]] = None
    reconstructed_from: Optional[List[Ark]] = None

    # in regular schemas but not export_test schema, unattested in data
    # think this got replaced with desc_provenance and/or image_provenance
    dig_provenance: Optional[DigProvenance] = None

    # found in export_test schema but not other schemas, seems to be used in all data
    desc_provenance: Optional[DescProvenance] = None
    image_provenance: Optional[ImageProvenance] = None

    # not in the schemas, found in the export_test data but not elsewhere
    has_bind: Optional[bool] = None


class ManuscriptObjectUnmerged(ManuscriptObject):
    part: List[PartUnmerged]
    layer: List[LayerStub] | None = Field(None, min_length=1)


class ManuscriptObjectMerged(ManuscriptObject):
    part: List[PartMerged]
    layer: List[InscribedLayerMerged] | None = Field(None, min_length=1)


class ManuscriptSolrRecord(PydanticBaseModel):
    id: str

    has_model_ssim: List[str] = ["Work"]
    visibility_ssi: str = "open"

    manuscript_json_ss: str
    descriptive_title_tesim: Set[str]
    #     return [self.manuscript_json_ss.shelfmark]
    uniform_title_tesim: Set[str]
    # uniform_title_sim = copy_field("uniform_title_tesim")
    # date_created_tesim: Set[str]
    human_readable_language_tesim: Set[str]
    # collection_ssi: str
    # name_fields_index_tesim: Set[str]
    # names_sim: Set[str]
