# pyright: reportInvalidTypeForm=false
# pylint: disable=too-many-lines
"""Pydantic classes for the data model."""

import re
from datetime import date, datetime
from enum import Enum
from typing import (
    Annotated,
    Any,
    Callable,
    List,
    Literal,
    Optional,
    Self,
    Set,
    TypeVar,
)
from uuid import UUID

import dateutil.parser
from pydantic import (
    AnyUrl,
    ConfigDict,
    Field,
    StringConstraints,
    computed_field,
    model_validator,
)
from pydantic import (
    BaseModel as PydanticBaseModel,
)
from pydantic.main import IncEx

SiblingModel = TypeVar('SiblingModel', bound=PydanticBaseModel)


class BaseModel(PydanticBaseModel):
    model_config = ConfigDict(extra='forbid', frozen=True)

    def model_dump(
        self,
        *,
        mode: Literal['json', 'python'] | str = 'python',
        include: IncEx | None = None,
        exclude: IncEx | None = None,
        context: Any | None = None,
        by_alias: bool | None = True,  # Overriding this
        exclude_unset: bool = True,  # Overriding this
        exclude_defaults: bool = True,  # Overriding this
        exclude_none: bool = True,  # Overriding this
        round_trip: bool = False,
        warnings: (bool | Literal['none', 'warn', 'error']) = True,
        fallback: Callable[[Any], Any] | None = None,
        serialize_as_any: bool = False,
    ) -> dict[str, Any]:
        return super().model_dump(
            mode=mode,
            include=include,
            exclude=exclude,
            context=context,
            by_alias=by_alias,
            exclude_unset=exclude_unset,
            exclude_defaults=exclude_defaults,
            exclude_none=exclude_none,
            round_trip=round_trip,
            warnings=warnings,
            fallback=fallback,
            serialize_as_any=serialize_as_any,
        )

    def model_dump_json(
        self,
        *,
        indent: int | None = None,
        include: IncEx | None = None,
        exclude: IncEx | None = None,
        context: Any | None = None,
        by_alias: bool | None = True,  # Overriding this
        exclude_unset: bool = True,  # Overriding this
        exclude_defaults: bool = True,  # Overriding this
        exclude_none: bool = True,  # Overriding this
        round_trip: bool = False,
        warnings: (bool | Literal['none', 'warn', 'error']) = True,
        fallback: Callable[[Any], Any] | None = None,
        serialize_as_any: bool = False,
    ) -> str:
        return super().model_dump_json(
            indent=indent,
            include=include,
            exclude=exclude,
            context=context,
            by_alias=by_alias,
            exclude_unset=exclude_unset,
            exclude_defaults=exclude_defaults,
            exclude_none=exclude_none,
            round_trip=round_trip,
            warnings=warnings,
            fallback=fallback,
            serialize_as_any=serialize_as_any,
        )

    # type: ignore
    def convert(self, cls: type[SiblingModel], **updated_data: Any) -> SiblingModel:
        data = self.model_dump() | updated_data
        return cls(**data)

    def deep_get(self, *names: str) -> set[Any]:
        result = set()

        for name in names:
            value = getattr(self, name, [])
            if isinstance(value, List):
                result.update(value)
            elif value:
                # Don't add if value == None
                result.add(value)

        for field_name in self.__class__.model_fields:
            field_value = getattr(self, field_name, [])
            if isinstance(field_value, List):
                for obj in field_value:
                    if hasattr(obj, 'deep_get'):
                        result.update(obj.deep_get(*names))
            else:
                if hasattr(field_value, 'deep_get'):
                    result.update(field_value.deep_get(*names))

        return result


NonEmptyStr = Annotated[
    str,
    StringConstraints(min_length=1),
]

Ark = Annotated[
    str,
    StringConstraints(pattern=r'^ark:/21198/([a-z]|[0-9])+'),
]


class ControlledTerm(BaseModel):
    id: NonEmptyStr
    label: NonEmptyStr


# generated by datamodel-codegen:
#   filename:  agent.schema.json
#   timestamp: 2025-05-28T17:21:15+00:00


def parse_date(input_date: str | int | date | datetime | None) -> int | None:
    """Most of our dates are 4-digit strings representing years. By default dateutil.parser"""
    if isinstance(input_date, str):
        if re.match(r'^\d\d\d\d$', input_date):
            return int(input_date)
        else:
            return dateutil.parser.parse(input_date).year
    elif isinstance(input_date, (date, datetime)):
        return input_date.year
    elif isinstance(input_date, (int)):
        return input_date
    else:
        # so it will raise a ValidationError
        return None


class Iso(BaseModel):
    not_before: int
    not_after: int

    @model_validator(mode='before')
    @classmethod
    def parse_inputs(cls, data: dict) -> dict:
        """By convention, single-year dates only have not_before. We want to copy that to not_after if it's empty."""

        data.setdefault('not_after', data.get('not_before'))
        return {
            'not_before': parse_date(data.get('not_before')),
            'not_after': parse_date(data.get('not_after')),
        }

    def get_years(self) -> set[int]:
        return set(range(self.not_before, self.not_after + 1))


class Date(BaseModel):
    value: Optional[NonEmptyStr] = None
    iso: Iso


class RelatedConceptSource(Enum):
    HAF = 'HAF'
    LoC = 'LoC'
    Perseus = 'Perseus'
    Pinakes = 'Pinakes'
    Pleiades = 'Pleiades'
    Syriaca = 'Syriaca'
    VIAF = 'VIAF'


class RelConItem(BaseModel):
    label: NonEmptyStr
    uri: AnyUrl
    source: RelatedConceptSource


class ReferenceNumberSource(Enum):
    CPG = 'CPG'
    CPL = 'CPL'
    TLG = 'TLG'


class RefnoItem(BaseModel):
    label: NonEmptyStr
    idno: NonEmptyStr
    source: ReferenceNumberSource


class BibItem(BaseModel):
    id: UUID
    type: ControlledTerm
    shortcode: Optional[str] = None  # TODO: required in JSON schema but not found in all data
    citation: Optional[str] = None  # TODO: required in JSON schema but not found in all data
    range: Optional[NonEmptyStr] = None
    alt_shelf: Optional[NonEmptyStr] = None
    url: Optional[NonEmptyStr] = None
    note: List[str] = []


class RelItem(BaseModel):
    id: NonEmptyStr
    label: NonEmptyStr


class RelAgentItem(BaseModel):
    id: Ark = Field(..., description='A unique Archival Resource Key (ARK)')
    source: List[str] = []
    rel: List[RelItem]


class RelPlaceItem(BaseModel):
    id: Ark = Field(..., description='A unique Archival Resource Key (ARK)')
    source: List[str] = []
    rel: List[RelItem]


class CataloguerItem(BaseModel):
    message: NonEmptyStr
    contributor: Optional[NonEmptyStr] = Field(
        None,
        description='The person responsible for the intellectual contributions made to the record via this change',
    )
    added_by: NonEmptyStr = Field(
        ...,
        description='The user account responsible for editing the JSON record, likely supplied by the content management system',
    )
    timestamp: datetime


class Agent(BaseModel):
    ark: Ark
    type: ControlledTerm
    pref_name: NonEmptyStr
    alt_name: List[NonEmptyStr] = []
    desc: Optional[NonEmptyStr] = None
    gender: Optional[ControlledTerm] = None
    birth: Optional[Date] = None
    death: Optional[Date] = None
    floruit: Optional[Date] = None
    rel_con: List[RelConItem] = []
    refno: List[RefnoItem] = []
    bib: List[BibItem] = []
    note: List[str] = []
    rel_agent: List[RelAgentItem] = []
    rel_place: List[RelPlaceItem] = []
    internal: List[str] = []
    cataloguer: List[CataloguerItem] = []


# generated by datamodel-codegen:
#   filename:  work.schema.json
#   timestamp: 2025-05-28T17:23:18+00:00


class Creation(BaseModel):
    value: Optional[NonEmptyStr] = None
    iso: Iso


# TODO: not attested
class Incipit(BaseModel):
    value: NonEmptyStr
    translation: List[str] = []
    source: List[str] = []


# TODO not attested
class Explicit(BaseModel):
    value: NonEmptyStr
    translation: List[str] = []
    source: List[str] = []


# TODO not attested
class RelWorkItem(BaseModel):
    id: Ark
    source: List[str] = []
    rel: List[RelItem]


class AssocNameItem(BaseModel):
    id: Optional[Ark] = None
    agent_record: Optional[Agent] = None
    value: Optional[NonEmptyStr] = None
    as_written: Optional[NonEmptyStr] = None
    role: ControlledTerm
    note: List[str] = []


class AssocNameItemMerged(AssocNameItem):
    agent_record: Optional[Agent] = None

    @model_validator(mode='after')
    def agent_record_loaded(self) -> Self:
        if self.id and not self.agent_record:
            raise ValueError('has agent id but agent_record not loaded')
        return self


class AssocNameItemUnmerged(AssocNameItem):
    agent_record: None = None


class ConceptualWork(BaseModel):
    ark: Ark
    pref_title: NonEmptyStr
    orig_lang: Optional[ControlledTerm] = None
    orig_lang_title: Optional[NonEmptyStr] = None
    alt_title: List[NonEmptyStr] = []
    desc: Optional[NonEmptyStr] = None
    genre: List[ControlledTerm] = []
    creator: List[AssocNameItemUnmerged] | List[AssocNameItemMerged] = []
    creation: Optional[Creation] = None
    incipit: Optional[Incipit] = None
    explicit: Optional[Explicit] = None
    rel_con: List[RelConItem] = []
    refno: List[RefnoItem] = []
    bib: List[BibItem] = []
    note: List[str] = []
    rel_work: List[RelWorkItem] = []
    rel_agent: List[RelAgentItem] = []
    rel_place: List[RelPlaceItem] = []
    internal: List[str] = []
    cataloguer: List[CataloguerItem] = []


class ConceptualWorkUnmerged(ConceptualWork):
    creator: List[AssocNameItemUnmerged] = []


class ConceptualWorkMerged(ConceptualWork):
    creator: List[AssocNameItemMerged] = []


# generated by datamodel-codegen:
#   filename:  text_unit.schema.json
#   timestamp: 2025-05-28T17:22:58+00:00


class WorkBriefCreator(BaseModel):
    id: Ark
    agent_record: Agent


class WorkStub(BaseModel):
    id: Ark


# TODO: what's up here?
class WorkBrief(BaseModel):
    desc_title: Optional[NonEmptyStr] = None
    creator: List[Ark] | List[WorkBriefCreator] = []
    genre: List[ControlledTerm] = []


class WorkBriefUnmerged(WorkBrief):
    creator: List[Ark] = []


class WorkBriefMerged(WorkBrief):
    creator: List[WorkBriefCreator] = []


class ExcerptItem(BaseModel):
    type: ControlledTerm
    locus: Optional[NonEmptyStr] = None
    as_written: Optional[NonEmptyStr] = None
    translation: List[str] = []
    note: List[str] = []


class Contents(BaseModel):
    label: Optional[NonEmptyStr] = None
    work_id: Optional[Ark] = None
    locus: Optional[NonEmptyStr] = None
    note: List[str] = []

    @model_validator(mode='after')
    def has_label_or_work_id(self) -> Self:
        if not (self.label or self.work_id):
            raise ValueError('`Contents.label` and `.work_id` cannot both be None')
        return self


class ContentsUnmerged(Contents):
    pass


class ContentsMerged(Contents):
    pref_title: Optional[NonEmptyStr] = None


class WorkWitItem(BaseModel):
    work: WorkBrief | WorkStub | ConceptualWorkMerged
    alt_title: Optional[str] = Field(
        None,
        description='An alternative title providing witness-specific information about the work',
    )
    as_written: Optional[NonEmptyStr] = None
    locus: Optional[NonEmptyStr] = None
    excerpt: List[ExcerptItem] = []
    contents: List[ContentsUnmerged] | List[ContentsMerged] = []
    note: List[str] = []
    bib: List[BibItem] = []


class WorkWitItemUnmerged(WorkWitItem):
    work: WorkBriefUnmerged | WorkStub
    contents: List[ContentsUnmerged] = []


class WorkWitItemMerged(WorkWitItem):
    work: WorkBriefMerged | ConceptualWorkMerged
    contents: List[ContentsMerged] = []


class ScriptItem(BaseModel):
    id: NonEmptyStr
    label: NonEmptyStr
    writing_system: str


class Place(BaseModel):
    ark: Ark
    pref_name: NonEmptyStr
    alt_name: List[NonEmptyStr] = []


class AssocPlaceItem(BaseModel):
    id: Optional[Ark] = None
    value: Optional[NonEmptyStr] = None
    as_written: Optional[NonEmptyStr] = None
    event: ControlledTerm
    note: List[str] = []


class AssocPlaceItemUnmerged(AssocPlaceItem):
    pass


class AssocPlaceItemMerged(AssocPlaceItem):
    place_record: Place | None = None

    @model_validator(mode='after')
    def has_place_record_if_possible(self) -> Self:
        if self.id and not self.place_record:
            raise ValueError(f'{self} has id {self.id} but no place_record loaded')
        return self


class AssocDateItem(BaseModel):
    value: NonEmptyStr
    iso: Optional[Iso] = None
    type: ControlledTerm
    as_written: Optional[NonEmptyStr] = None
    note: List[str] = []


class ParaItem(BaseModel):
    type: ControlledTerm
    locus: NonEmptyStr
    lang: List[ControlledTerm] = Field(..., min_length=1)
    script: List[ScriptItem] = []
    label: Optional[NonEmptyStr] = None
    as_written: Optional[NonEmptyStr] = None
    translation: List[str] = []
    assoc_name: List[AssocNameItemUnmerged] | List[AssocNameItemMerged] = []
    assoc_place: List[AssocPlaceItemUnmerged] | List[AssocPlaceItemMerged] = []
    assoc_date: List[AssocDateItem] = []
    note: List[str] = []


class ParaItemUnmerged(ParaItem):
    assoc_name: List[AssocNameItemUnmerged] = []
    assoc_place: List[AssocPlaceItemUnmerged] = []


class ParaItemMerged(ParaItem):
    assoc_name: List[AssocNameItemMerged] = []
    assoc_place: List[AssocPlaceItemMerged] = []


class NoteItem(BaseModel):
    type: ControlledTerm
    value: Optional[NonEmptyStr]


class DescProvenanceProgramItem(BaseModel):
    label: str
    description: str


class DescProvenance(BaseModel):
    program: List[DescProvenanceProgramItem] = []
    rights: Optional[str] = None


class TextUnit(BaseModel):
    ark: Ark
    reconstruction: bool
    label: NonEmptyStr
    summary: Optional[NonEmptyStr] = None
    locus: Optional[NonEmptyStr] = None
    lang: List[ControlledTerm] = Field(..., min_length=1)
    work_wit: List[WorkWitItemUnmerged] | List[WorkWitItemMerged] = Field(..., min_length=1)
    para: List[ParaItemUnmerged] | List[ParaItemMerged] = []
    features: List[ControlledTerm] = []
    note: List[NoteItem] = []
    bib: List[BibItem] = []
    cataloguer: List[CataloguerItem] = []
    reconstructed_from: List[Ark] = []
    parent: List[Ark] = Field(..., min_length=1)
    internal: List[str] = []
    desc_provenance: Optional[DescProvenance] = None  # TODO found in data, not schema


class TextUnitUnmerged(TextUnit):
    work_wit: List[WorkWitItemUnmerged] = Field(..., min_length=1)
    para: List[ParaItemUnmerged] = []


class TextUnitMerged(TextUnit):
    work_wit: List[WorkWitItemMerged] = Field(..., min_length=1)
    para: List[ParaItemMerged] = []


# generated by datamodel-codegen:
#   filename:  layer.schema.json
#   timestamp: 2025-05-28T17:21:54+00:00

# from __future__ import annotations

# from datetime import datetime
# from typing import List, Optional
# from uuid import UUID

# from pydantic import AnyUrl, BaseModel, Field, constr


class WritingItem(BaseModel):
    script: List[ScriptItem] = Field(..., min_length=1)
    locus: Optional[NonEmptyStr] = None
    note: List[str] = []


class InkItem(BaseModel):
    locus: Optional[NonEmptyStr] = None
    color: List[str] = []
    note: List[str] = []


class LayoutItem(BaseModel):
    locus: Optional[NonEmptyStr] = None
    columns: Optional[str] = None
    lines: Optional[str] = None
    dim: Optional[NonEmptyStr] = Field(
        None,
        description="A string expression of an object's dimensions, whether manuscript block, folio, or writing area",
    )
    note: List[str] = []


class LayerTextUnit(BaseModel):
    id: Ark = Field(..., description='A unique Archival Resource Key (ARK)')
    label: NonEmptyStr
    locus: Optional[NonEmptyStr] = None


class LayerTextUnitUnmerged(LayerTextUnit):
    pass


class LayerTextUnitMerged(LayerTextUnit):
    text_unit_record: TextUnitMerged


class Ms(BaseModel):
    label: NonEmptyStr
    id: Optional[Ark] = None
    url: Optional[AnyUrl] = None


class RelatedMs(BaseModel):
    type: ControlledTerm
    label: NonEmptyStr
    note: List[str] = []
    mss: List[Ms] = Field(..., min_length=1)


class InscribedLayer(BaseModel):
    ark: Ark
    reconstruction: bool
    state: ControlledTerm = Field(..., description='The current state of the inscribed layer')
    label: NonEmptyStr
    locus: Optional[NonEmptyStr] = None
    summary: Optional[NonEmptyStr] = None
    extent: Optional[NonEmptyStr] = Field(
        None,
        description='The extent, expressed in number of folios, which comprise the manuscript object',
    )
    writing: List[WritingItem] = Field(..., min_length=1)
    ink: List[InkItem] = []
    layout: List[LayoutItem] = []
    text_unit: List[LayerTextUnitUnmerged] | List[LayerTextUnitMerged] = Field(..., min_length=1)
    para: List[ParaItemUnmerged] | List[ParaItemMerged] = []
    assoc_date: List[AssocDateItem] = []
    assoc_name: List[AssocNameItemUnmerged] | List[AssocNameItemMerged] = []
    assoc_place: List[AssocPlaceItemUnmerged] | List[AssocPlaceItemMerged] = []
    features: List[ControlledTerm] = []
    related_mss: List[RelatedMs] = []
    note: List[NoteItem] = []
    bib: List[BibItem] = []
    cataloguer: List[CataloguerItem] = []
    reconstructed_from: List[Ark] = []
    parent: List[Ark] = Field(..., min_length=1)
    internal: List[str] = []
    desc_provenance: Optional[DescProvenance] = None  # TODO found in data, not schema


class InscribedLayerUnmerged(InscribedLayer):
    text_unit: List[LayerTextUnitUnmerged] = Field(..., min_length=1)
    para: List[ParaItemUnmerged] = []
    assoc_name: List[AssocNameItemUnmerged] = []
    assoc_place: List[AssocPlaceItemUnmerged] = []


class InscribedLayerMerged(InscribedLayer):
    text_unit: List[LayerTextUnitMerged] = Field(..., min_length=1)
    para: List[ParaItemMerged] = []
    assoc_name: List[AssocNameItemMerged] = []
    assoc_place: List[AssocPlaceItemMerged] = []

    def get_dates(self, date_type: str | None = None) -> List[AssocDateItem]:
        return [
            date
            for date in (self.assoc_date or [])
            if date_type is None or date.type.id == date_type
        ]


# generated by datamodel-codegen:
#   filename:  ms_obj.schema.json
#   timestamp: 2025-05-28T17:22:16+00:00

# from __future__ import annotations

# from datetime import datetime
# from enum import Enum
# from typing import List, Optional
# from uuid import UUID

# from pydantic import AnyUrl, BaseModel, Field, constr


class ManuscriptLayer(BaseModel):
    id: Ark
    label: NonEmptyStr
    type: ControlledTerm
    layer_record: Optional[InscribedLayerMerged] = None
    locus: Optional[NonEmptyStr] = None

    def get_dates(self, date_type: str | None = None) -> list[AssocDateItem]:
        if self.layer_record:
            return self.layer_record.get_dates(date_type=date_type)
        else:
            return []


class ManuscriptLayerUnmerged(ManuscriptLayer):
    layer_record: None = None


class ManuscriptLayerMerged(ManuscriptLayer):
    layer_record: InscribedLayerMerged


class UndertextManuscriptLayerMerged(ManuscriptLayer):
    id: Ark = Field(..., serialization_alias='uto_layer_ark')

    layer_record: None = None

    uto_ms_ark: Optional[Ark] = None

    script: List[str] = []
    lang: List[str] = []
    orig_date: List[AssocDateItem] = []

    @model_validator(mode='after')
    def undertext_type(self) -> Self:
        if self.type != ControlledTerm(id='undertext', label='Undertext'):
            raise ValueError('UndertextManuscriptLayerMerged records must have type="undertext"')
        return self


class Part(BaseModel):
    label: Optional[NonEmptyStr] = None
    summary: Optional[NonEmptyStr] = None
    locus: Optional[NonEmptyStr] = None
    support: List[ControlledTerm] = Field(..., min_length=1)
    extent: Optional[NonEmptyStr] = Field(
        None,
        description='The extent, expressed in number of folios, which comprise the manuscript object',
    )
    dim: Optional[NonEmptyStr] = Field(
        None,
        description="A string expression of an object's dimensions, whether manuscript block, folio, or writing area",
    )
    layer: List[ManuscriptLayerUnmerged] = Field(..., min_length=1)
    para: List[ParaItemUnmerged] | List[ParaItemMerged] = []
    note: List[NoteItem] = []
    related_mss: List[RelatedMs] = []


class PartUnmerged(Part):
    para: List[ParaItemUnmerged] = []


class PartMerged(Part):
    layer: List[ManuscriptLayerUnmerged] = Field(..., max_length=0, exclude=True)
    ot_layer: List[ManuscriptLayerMerged] = Field(..., min_length=1)
    guest_layer: List[ManuscriptLayerMerged] = []
    uto: List[UndertextManuscriptLayerMerged] = []
    para: List[ParaItemMerged] = []


class LocationItem(BaseModel):
    id: NonEmptyStr
    collection: Optional[str] = None
    repository: NonEmptyStr


class ViscodexItem(BaseModel):
    type: ControlledTerm
    label: NonEmptyStr
    url: AnyUrl


class TextDirection(Enum):
    right_to_left = 'right-to-left'
    top_to_bottom = 'top-to-bottom'
    bottom_to_top = 'bottom-to-top'


class Behavior(Enum):
    paged = 'paged'
    individuals = 'individuals'


class IiifItem(BaseModel):
    type: ControlledTerm
    manifest: AnyUrl
    text_direction: Optional[TextDirection] = None
    behavior: Optional[Behavior] = None
    thumbnail: Optional[AnyUrl] = None


# TODO only used in unattested class DigProvenance
class Image(BaseModel):
    camera_operator: List[str] = []
    imaging_date: Optional[str] = None
    delivery: Optional[str] = None
    msi_processing: List[str] = Field(
        [],
        description='Names of the person(s) responsible for processing the MSI data for this record',
    )
    program: Optional[str] = None
    condition_category: Optional[str] = None
    note: List[str] = []


# TODO only used in unattested class DigProvenance
class Description(BaseModel):
    program: str
    note: List[str] = []


# TODO class not attested in data, replace by DescProvenance and ImageProvenance?
class DigProvenance(BaseModel):
    images: List[Image] = []
    descriptions: List[Description] = []
    image_rights: NonEmptyStr
    metadata_rights: NonEmptyStr


# TODO attested in all data but only found in the export_test schema
class ImageProvenanceProgramItem(BaseModel):
    label: Optional[str] = None
    description: Optional[str] = None
    camera_operator: List[str] = []
    imaging_date: Optional[str] = None
    delivery: Optional[str] = None
    msi_processing: List[str] = Field(
        [],
        description='Names of the person(s) responsible for processing the MSI data for this record',
    )
    condition_category: Optional[str] = None
    note: List[str] = []

    # TODO: not found in schemas, attested in data
    imaging_system: Optional[str] = None


# TODO attested in all data but only found in the export_test schema
class ImageProvenance(BaseModel):
    program: List[ImageProvenanceProgramItem] = []
    rights: Optional[NonEmptyStr] = (
        None  # TODO schema defines as not optional but gives None as default
    )


class ManuscriptObject(BaseModel):
    ark: Ark = Field(..., description='A unique Archival Resource Key (ARK)')
    reconstruction: bool
    type: ControlledTerm
    shelfmark: NonEmptyStr
    summary: Optional[NonEmptyStr] = None
    extent: Optional[NonEmptyStr] = Field(
        ...,
        description='The extent, expressed in number of folios, which comprise the manuscript object',
    )
    weight: Optional[NonEmptyStr] = Field(
        None, description="A string expression of the manuscript object's weight"
    )
    dim: Optional[NonEmptyStr] = Field(
        None,
        description="A string expression of an object's dimensions, whether manuscript block, folio, or writing area",
    )
    state: ControlledTerm = Field(..., description='The current state of the manuscript object')
    fol: Optional[NonEmptyStr] = Field(
        None,
        description='A string expressing the foliation of the object in a semi-controlled format',
    )
    coll: Optional[NonEmptyStr] = Field(
        None,
        description='A string expressing the collation of the object following a semi-controlled format, such as a collational formula',
    )
    features: List[ControlledTerm] = []
    part: List[Part] | List[PartUnmerged] | List[PartMerged] = Field(..., min_length=1)
    layer: List[ManuscriptLayerUnmerged] = []
    para: List[ParaItemUnmerged] | List[ParaItemMerged] = []
    location: List[LocationItem]
    assoc_date: List[AssocDateItem] = []
    assoc_name: List[AssocNameItemMerged] | List[AssocNameItemUnmerged] = []
    assoc_place: List[AssocPlaceItemUnmerged] | List[AssocPlaceItemMerged] = []
    note: List[NoteItem] = []
    related_mss: List[RelatedMs] = []
    viscodex: List[ViscodexItem] = []
    bib: List[BibItem] = []
    iiif: List[IiifItem] = []
    internal: List[str] = []
    cataloguer: List[CataloguerItem] = []
    reconstructed_from: List[Ark] = []

    # in regular schemas but not export_test schema, unattested in data
    # think this got replaced with desc_provenance and/or image_provenance
    dig_provenance: Optional[DigProvenance] = None

    # found in export_test schema but not other schemas, seems to be used in all data
    desc_provenance: Optional[DescProvenance] = None
    image_provenance: Optional[ImageProvenance] = None

    # not in the schemas, found in the export_test data but not elsewhere
    has_bind: Optional[bool] = None


class ManuscriptObjectUnmerged(ManuscriptObject):
    part: List[PartUnmerged]
    assoc_name: List[AssocNameItemUnmerged] = []
    assoc_place: List[AssocPlaceItemUnmerged] = []
    para: List[ParaItemUnmerged] = []


class ManuscriptObjectMerged(ManuscriptObject):
    part: List[PartMerged]

    layer: List[ManuscriptLayerUnmerged] = Field([], max_length=0, exclude=True)
    ot_layer: List[ManuscriptLayerMerged] = []
    guest_layer: List[ManuscriptLayerMerged] = []
    uto: List[UndertextManuscriptLayerMerged] = []

    assoc_name: List[AssocNameItemMerged] = []
    assoc_place: List[AssocPlaceItemMerged] = []

    para: List[ParaItemMerged] = []


class ManuscriptSolrRecord(PydanticBaseModel):
    ms_obj: ManuscriptObjectMerged = Field(..., exclude=True)

    @computed_field
    def id(self) -> str:
        return self.ms_obj.ark

    @computed_field
    def has_model_ssim(self) -> List[str]:
        return ['Work']

    @computed_field
    def visibility_ssi(self) -> str:
        return 'open'

    @computed_field
    def manuscript_json_ss(self) -> str:
        return self.ms_obj.model_dump_json()

    # @computed_field
    # def descriptive_title_tesim(self) -> Set[str]:
    #     return {}

    # @computed_field  #     return [self.manuscript_json_ss.shelfmark]
    # def uniform_title_tesim(self) -> Set[str]:
    #     return {}

    # uniform_title_sim = copy_field("uniform_title_tesim")

    # @computed_field  # date_created_tesim: Set[str]
    # def human_readable_language_tesim(self) -> Set[str]:
    #     pass

    # collection_ssi: str
    # name_fields_index_tesim: Set[str]
    # names_sim: Set[str]

    @computed_field
    def year_isim(self) -> Set[int]:
        return {
            year
            for layer in self.ms_obj.ot_layer
            for date in layer.get_dates(date_type='origin')
            for year in (date.iso.get_years() if date.iso else [])
        } | {
            year
            for part in self.ms_obj.part
            for layer in part.ot_layer
            for date in layer.get_dates(date_type='origin')
            for year in (date.iso.get_years() if date.iso else [])
        }
